### ISSUE TITLE
Overall data release structure

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/drb-temp-data-release-v2#4]
1. Spatial data [all locally built in `delaware-model-prep`]
- [x] river shapefiles [delaware-model-prep]
- [x] river segment metadata [delaware-model-prep]
- [x] reservoir shapefiles [lake-temp-model-prep]
- [x] reservoir metadata [delaware-model-prep?]
- [x] site shapefile [delaware-model-prep]
- [x] site metadata [delaware-model-prep]

2. Observations [all locally built in `delaware-model-prep` but with some other upstream pipeline dependencies]
- [x] river temperature observations raw
- [x] river temperature observations aggregated to single value per reach-day
- [x] flow observations
- [x] reservoir levels
- [x] reservoir releases
- [x] reservoir temperature observations
- [x] reservoir diversions

3. Driver data
- [x] **NEW** gridMET - on Caldera, which Jeff or @msleckman can point us to
- [x] **NEW** GEFS historical/reanalysis product - @jzwart will point us to Caldera location
- [x] PRMS-SNTemp ins/outs - built [here](https://code.usgs.gov/wma/wp/run-prms-sntemp) and stored in `/caldera/projects/usgs/water/iidd/datasci/water-prediction/run-prms-sntemp/4_model_run/out/uncal_sntemp_input_output.nc`
- [x] distance matrix (or does this go in spatial data?) - locally build in `delaware-model-prep`

**Comment by jzwart** [comment]
>NEW GEFS historical/reanalysis product - @jzwart will point us to Caldera location 

It's here and ready to go `/caldera/projects/usgs/water/iidd/datasci/water-prediction/run-pgdl-da-jzwart/2_model_prep/in/reanalysis_gefs_fy22.csv` . Let me know if you have questions re: metadata.

**Comment by msleckman** [comment]
> NEW gridMET - on Caldera, which @Jeff or @msleckman can point us to

Most recent gridmet dataset from @jsadler2:	
`/caldera/projects/usgs/water/impd/pump/gridmet/drb_gridmet_tools/data/out/drb_climate_2022_04_06.nc` 

Let me know if there are any questions or concerns about this input driver dataset.

**Comment by msleckman** [comment]
Updated to hpc data_releases repo: 
* Driver data added. Still awaiting csv vrn of gridmet up to 04_06 or later;
* observations need to be `scp` and have no done so successfully. Log in credentials issue. 
* Ended up creating 3 sub-folder in `data_releases/drb-temp-data-release-v2/in_data/` : 
```
in_data/
|_ 01_spatial
|_ 02_observations
   - NYC_DEP_reservoir_waterlevels.rds # - not yet copied
   - drb_daily_reservoir_temps.rds # - not yet copied
   - drb_reservoirs_waterlevels_munged.rds # - not yet copied
   - interpolated_daily_reservoir_water_budget_components.csv # - not yet copied
   - reservoir_diversions.csv # - not yet copied
   - reservoir_releases_by_type_drb.csv # - not yet copied
|_ 03_driver
   - drb_climate_2022_04_06.nc # - copied
   - reanalysis_gefs_fy22.csv  # - copied
```

Spatial files still need to be added to local in_data folder.

**Comment by msleckman** [comment]
* All driver datasets added to caldera `in_data/03_driver/` + paths have been modified in repo. 
* The [checked](url) obs datasets are all found in caldera in `in_data/02_observations/` + paths have been modified in repo to work with the caldera dir. 
* Repo just pulled to caldera wd so that what's in caldera is up to date with changes to repo. 
* Spatial files need to be added 

New issue re: zipping `.nc` files #10

**Comment by msleckman** [comment]
@limnoliver I've transferred over some of the files I figure match with the spatial data files, based on the drb data release template I have: 

**in_data/01_spatial**
* _river shapefiles :_ 
- `network.rds` 
- `segments_relative_to_reservoirs.rds`
* _reservoir shapefiles:_ 
- `reservoir_features.csv`
- `reservoir_interpolated_daily_water_budget_components.csv`
* _site shapefile:_
- `drb_filtered_sites.rds`
