### ISSUE TITLE
First steps

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/drb-temp-data-release-v2#5]
- [x] create IPDS record. Authors should include: Margaux + Jake + Sam + Alison...Sam will figure out the rest
- [x] create SB item + child items that reflect the structure in #4 
- [x] Title: Data to support modeling water temperature in the Delaware River Basin
- [x] Product Summary: Data release to support multiple modeling efforts in the Delaware River Basin
- [x] team name could potentially be "AI/ML task within IWP PUMP"
- [x] edit the files Sam added to this repository to reflect the child item structure, including the new SB IDs for the parent and child items.
- [x] add gridMET to 3_drivers section + metadata to the appropriate in_text file

**Comment by msleckman** [comment]
- [ ] Add cooperator's ORCID to excel

**Comment by msleckman** [comment]
Branch addressing this issue found in my fork [msleckman/drb-temp-data-release-v2:file_structure_edits_1](https://github.com/msleckman/drb-temp-data-release-v2/tree/file_structure_edits_1)

SB item for [Data release to support multiple modeling efforts in the Delaware River Basin](https://www.sciencebase.gov/catalog/item/623e4418d34e915b67d7dd78) containing 3 child items (01_spatial, 02_observations, 03_driver)

In line comments added to code in forked branch.

**Comment by msleckman** [comment]
gridmet source file currently a local path. Will switch to caldera path.
